### ISSUE TITLE
Insert() panics after Delete()

### ISSUE THREAD

**Issue by aletheia7** [gilramir/critbit#1]
Insert() panics after Delete()

#### Example Code
```go
package main

import (
        "github.com/gilramir/critbit"
        "log"
)

func main() {
        log.SetFlags(0)
        trie := critbit.New(128)
        for i, key := range []string{
                "red",
                "blue",
                "green",
                "yellow",
        } {
                log.Println(key)
                trie.Insert(key, 1)
                if i == 2 {
                        trie.Delete(key)
                }
        }
}
```
#### Output
```
red
blue
green
yellow
panic: interface conversion: interface is int64, not uint32

goroutine 1 [running]:
panic(0x811da00, 0x184153a0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x331
tt/vendor/github.com/gilramir/critbit.(*Critbit).addExternalRef(0x18447f74, 0x8132f90, 0x6, 0x81184a0, 0x18410ae0, 0x0, 0x0, 0x0)
        /home/<...>/go/src/tt/vendor/github.com/gilramir/critbit/tree.go:31 +0x1c5
tt/vendor/github.com/gilramir/critbit.(*Critbit).Insert(0x18447f74, 0x8132f90, 0x6, 0x81184a0, 0x18410ae0, 0x18473001, 0x0, 0x0)
        /home/<...>/go/src/tt/vendor/github.com/gilramir/critbit/insert.go:54 +0x384
main.main()
        /home/<...>/go/src/tt/t.go:24 +0x293
```
#### Expected Output
```
red
blue
green
yellow
```

**Comment by gilramir** [comment]
Thanks for reporting this issue. I have fixed this today in commit a4735f6799d547224885c38c537482832605b808
